export const LIST_ALL_ORDER = "LIST_ALL_ORDER";
export const ADD_ORDER = "ADD_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";

export const ORDERS_LOADING = "ORDERS_LOADING";
export const ADD_ORDER_ERRORS = 'ADD_ORDER_ERRORS';
export const LISTALL_ORDER_ERRORS = 'LISTALL_ORDER_ERRORS';
export const CLEAR_ORDER_ERRORS = 'CLEAR_ORDER_ERRORS';
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL';
export const CLEAR_ACTION ='CLEAR_ACTION';
export const SEARCH_ORDER = 'SEARCH_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const GET_ORDER_EDIT = 'GET_ORDER_EDIT';
export const UPDATE_ORDER_ERRORS = 'UPDATE_ORDER_ERRORS';

export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const ADD_PRODUCT_ERRORS = 'ADD_PRODUCT_ERRORS';
export const DELETE_PRODUCT_ERRORS = 'DELETE_PRODUCT_ERRORS';
export const LISTALL_PRODUCT_ERRORS = 'LISTALL_PRODUCT_ERRORS';
export const CLEAR_PRODUCT_ERRORS = 'CLEAR_PRODUCT_ERRORS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';
export const CLEAR_ACTION_PRODUCT ='CLEAR_ACTION_PRODUCT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_ERRORS = 'UPDATE_PRODUCT_ERRORS';
export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';

export const GET_ALL_CUSTOMER = 'GET_ALL_CUSTOMER';
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";

export const CUSTOMERS_LOADING = "CUSTOMERS_LOADING";
export const ADD_CUSTOMER_ERRORS = 'ADD_CUSTOMER_ERRORS';
export const DELETE_CUSTOMER_ERRORS = 'DELETE_CUSTOMER_ERRORS';
export const LISTALL_CUSTOMER_ERRORS = 'LISTALL_CUSTOMER_ERRORS';
export const CLEAR_CUSTOMER_ERRORS = 'CLEAR_CUSTOMER_ERRORS';
export const ADD_CUSTOMER_FAIL = 'ADD_CUSTOMER_FAIL';
export const CLEAR_ACTION_CUSTOMER ='CLEAR_ACTION_CUSTOMER';
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_ERRORS = 'UPDATE_CUSTOMER_ERRORS';
export const GET_CUSTOMER_EDIT = 'GET_CUSTOMER_EDIT';

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN = "LOGIN";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


export const GET_PRICE_FROM_PRODUCT = 'GET_PRICE_FROM_PRODUCT';

export const OPEN_MODAL = 'OPEN_MODAL';