export const GET_ALL_DEVICE = 'GET_ALL_DEVICE';
export const GET_ALL_DEVICE_SUCCESS = 'GET_ALL_DEVICE_SUCCESS';
export const GET_ALL_DEVICE_FAIL = 'GET_ALL_DEVICE_FAIL';

export const SEARCH_DEVICE = 'SEARCH_DEVICE';
export const SEARCH_DEVICE_SUCCESS = 'SEARCH_DEVICE_SUCCESS';
export const SEARCH_DEVICE_FAIL = 'SEARCH_DEVICE_FAIL';

export const GET_ID_DEVICE = 'GET_ID_DEVICE';
export const GET_ID_DEVICE_SUCCESS = 'GET_ID_DEVICE_SUCCESS';
export const GET_ID_DEVICE_FAIL = 'GET_ID_DEVICE_FAIL';

export const ADD_DEVICE = 'ADD_DEVICE';
export const ADD_DEVICE_SUCCESS = 'ADD_DEVICE_SUCCESS';
export const ADD_DEVICE_FAIL = 'ADD_DEVICE_FAIL';

export const DELETE_DEVICE = 'DELETE_DEVICE';
export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS';
export const DELETE_DEVICE_FAIL = 'DELETE_DEVICE_FAIL';

export const UPDATE_DEVICE = 'UPDATE_DEVICE';
export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';
export const UPDATE_DEVICE_NOTE = 'UPDATE_DEVICE_NOTE';
export const UPDATE_DEVICE_FAIL = 'UPDATE_DEVICE_FAIL';
export const SET_DEVICE_EDITING ='SET_DEVICE_EDITING';