export const GET_ALL_MQTT = 'GET_ALL_MQTT';
export const GET_ALL_MQTT_SUCCESS = 'GET_ALL_MQTT_SUCCESS';
export const GET_ALL_MQTT_FAIL = 'GET_ALL_MQTT_FAIL';

export const SEARCH_MQTT = 'SEARCH_MQTT';
export const SEARCH_MQTT_SUCCESS = 'SEARCH_MQTT_SUCCESS';
export const SEARCH_MQTT_FAIL = 'SEARCH_MQTT_FAIL';

export const GET_ID_MQTT = 'GET_ID_MQTT';
export const GET_ID_MQTT_SUCCESS = 'GET_ID_MQTT_SUCCESS';
export const GET_ID_MQTT_FAIL = 'GET_ID_MQTT_FAIL';

export const ADD_MQTT = 'ADD_MQTT';
export const ADD_MQTT_SUCCESS = 'ADD_MQTT_SUCCESS';
export const ADD_MQTT_FAIL = 'ADD_MQTT_FAIL';

export const DELETE_MQTT = 'DELETE_MQTT';
export const DELETE_MQTT_SUCCESS = 'DELETE_MQTT_SUCCESS';
export const DELETE_MQTT_FAIL = 'DELETE_MQTT_FAIL';

export const UPDATE_MQTT = 'UPDATE_MQTT';
export const UPDATE_MQTT_SUCCESS = 'UPDATE_MQTT_SUCCESS';
export const UPDATE_MQTT_NOTE = 'UPDATE_MQTT_NOTE';
export const UPDATE_MQTT_FAIL = 'UPDATE_MQTT_FAIL';
export const SET_MQTT_EDITING ='SET_MQTT_EDITING';